/*
  # Seed Products Data

  Insert initial coffee products into the products table
*/

INSERT INTO products (
  name,
  description,
  price,
  original_price,
  category,
  images,
  main_image,
  ingredients,
  nutrition,
  instructions,
  badges,
  rating,
  review_count,
  stock,
  sku,
  is_featured,
  tags
) VALUES 
(
  'Cafe at Once Latte',
  'Rich, bold espresso concentrate perfect for your daily coffee ritual. Made from premium Arabica beans.',
  199.00,
  235.00,
  'concentrate',
  ARRAY['https://res.cloudinary.com/dtcsms7zn/image/upload/v1751554159/WhatsApp_Image_2025-07-03_at_20.18.31_mfvrpe.jpg'],
  'https://res.cloudinary.com/dtcsms7zn/image/upload/v1751554159/WhatsApp_Image_2025-07-03_at_20.18.31_mfvrpe.jpg',
  ARRAY['100% Arabica Coffee', 'Natural Flavors'],
  '{"calories": 5, "caffeine": 120, "sugar": 0}',
  ARRAY['Peel the concentrate tube', 'Press into 4-6 oz of hot or cold water', 'Stir and enjoy your perfect espresso'],
  ARRAY['No Sugar', 'Gluten Free', 'Organic'],
  4.8,
  234,
  100,
  'CAO-LATTE-001',
  true,
  ARRAY['coffee', 'latte', 'concentrate', 'arabica']
),
(
  'Cafe at Once Americano',
  'Smooth and balanced Americano concentrate for the perfect cup every time.',
  199.00,
  235.00,
  'concentrate',
  ARRAY['https://res.cloudinary.com/dtcsms7zn/image/upload/v1751554787/WhatsApp_Image_2025-07-03_at_20.19.40_ykl6vs.jpg'],
  'https://res.cloudinary.com/dtcsms7zn/image/upload/v1751554787/WhatsApp_Image_2025-07-03_at_20.19.40_ykl6vs.jpg',
  ARRAY['100% Arabica Coffee', 'Natural Flavors'],
  '{"calories": 5, "caffeine": 95, "sugar": 0}',
  ARRAY['Peel the concentrate tube', 'Press into 6-8 oz of hot or cold water', 'Stir and enjoy your perfect Americano'],
  ARRAY['No Sugar', 'Gluten Free'],
  4.7,
  189,
  100,
  'CAO-AMER-002',
  true,
  ARRAY['coffee', 'americano', 'concentrate', 'arabica']
),
(
  'Cafe at Once Tea & Coffee',
  'Smooth, refreshing cold brew concentrate with low acidity and natural sweetness.',
  199.00,
  235.00,
  'concentrate',
  ARRAY['https://res.cloudinary.com/dtcsms7zn/image/upload/v1751556812/Frame_32_uwtjqy.png'],
  'https://res.cloudinary.com/dtcsms7zn/image/upload/v1751556812/Frame_32_uwtjqy.png',
  ARRAY['100% Arabica Coffee', 'Natural Flavors'],
  '{"calories": 5, "caffeine": 110, "sugar": 0}',
  ARRAY['Peel the concentrate tube', 'Press into 6-8 oz of cold water or milk', 'Add ice and enjoy your cold brew'],
  ARRAY['No Sugar', 'Organic', 'Cold Brew'],
  4.9,
  312,
  100,
  'CAO-TCOF-003',
  true,
  ARRAY['coffee', 'tea', 'concentrate', 'cold-brew']
),
(
  'Cafe at Once Mocha',
  'Rich chocolate and coffee blend in a convenient tube format.',
  199.00,
  235.00,
  'tube',
  ARRAY['https://res.cloudinary.com/dtcsms7zn/image/upload/v1751556810/Frame_31_rflj4i.png'],
  'https://res.cloudinary.com/dtcsms7zn/image/upload/v1751556810/Frame_31_rflj4i.png',
  ARRAY['Arabica Coffee', 'Natural Cocoa', 'Natural Flavors'],
  '{"calories": 15, "caffeine": 85, "sugar": 2}',
  ARRAY['Peel the tube', 'Press into 6 oz of hot milk or water', 'Stir well for the perfect mocha'],
  ARRAY['No Added Sugar', 'Real Cocoa'],
  4.6,
  156,
  100,
  'CAO-MOCH-004',
  false,
  ARRAY['coffee', 'mocha', 'chocolate', 'tube']
),
(
  'Cafe at Once Espresso',
  'Creamy vanilla latte with natural Espresso extract and premium coffee.',
  379.00,
  447.00,
  'flavored',
  ARRAY['https://res.cloudinary.com/dtcsms7zn/image/upload/v1751608473/Frame_33_oyik7i.png'],
  'https://res.cloudinary.com/dtcsms7zn/image/upload/v1751608473/Frame_33_oyik7i.png',
  ARRAY['Arabica Coffee', 'Natural Espresso Extract', 'Natural Flavors'],
  '{"calories": 20, "caffeine": 90, "sugar": 3}',
  ARRAY['Peel the tube', 'Press into 6 oz of hot milk', 'Stir and enjoy your vanilla latte'],
  ARRAY['Real Espresso', 'No Artificial Flavors'],
  4.5,
  143,
  100,
  'CAO-ESPR-005',
  true,
  ARRAY['coffee', 'espresso', 'premium', 'flavored']
),
(
  'Cafe at Once Cold Brew II',
  'Sweet and smooth caramel macchiato with rich espresso and natural caramel.',
  199.00,
  235.00,
  'flavored',
  ARRAY['https://res.cloudinary.com/dtcsms7zn/image/upload/v1751556808/Frame_30_dmzmur.png'],
  'https://res.cloudinary.com/dtcsms7zn/image/upload/v1751556808/Frame_30_dmzmur.png',
  ARRAY['Arabica Coffee', 'Natural Caramel', 'Natural Flavors'],
  '{"calories": 25, "caffeine": 95, "sugar": 4}',
  ARRAY['Peel the tube', 'Press into 6 oz of steamed milk', 'Create beautiful latte art if desired'],
  ARRAY['Real Caramel', 'Premium Coffee', 'Coming Soon'],
  4.7,
  198,
  100,
  'CAO-CBRU-006',
  false,
  ARRAY['coffee', 'cold-brew', 'caramel', 'flavored']
);